daily_notes_file: "~/Documents/notes/jrnl/daily.md"
daily_output_dir: "~/Documents/notes/daily"
weekly_output_dir: "~/Documents/notes/Weekly"
meeting_notes_output_dir: "~/Documents/notes/meetingnotes"
base_url: "https://api.openai.com/v1/"
api_key: ""
reminders_list: ""
model: "gpt-4o"
chunking_model: "gpt-4o-mini"
learnings_file: "~/Documents/notes/jrnl/learnings.md"
learnings_output_dir: "~/Documents/notes/learnings"

# Notes directory for knowledge base
notes_base_dir: "~/Documents/notes"  # Base directory for all notes
knowledge_base:
  exclude_patterns: 
    - "*.excalidraw.md"  # Exclude Excalidraw files
    - "templates/*"       # Exclude template directory
    - ".obsidian/*"      # Exclude Obsidian config
    - ".trash/*"         # Exclude trash
    - ".git/*"           # Exclude git directory

# Vector store settings
vector_store:
  path: "~/Documents/notes/.vector_store"  # Local ChromaDB storage
  chunk_size_min: 50   # Minimum characters per chunk
  chunk_size_max: 500  # Maximum characters per chunk
  similarity_threshold: 0.85  # Minimum similarity score for matches

# Chunking strategy configuration
chunking_strategy: "semantic"  # Options: "semantic" or "paragraph"
chunking_config:
  semantic:
    min_size: 50    # Minimum characters per chunk
    max_size: 500   # Maximum characters per chunk
  paragraph:
    max_length: 500  # Maximum length of paragraph chunks
    overlap: 50      # Number of characters to overlap between chunks
