daily_notes_file: "~/Documents/notes/jrnl/daily.md"
daily_output_dir: "~/Documents/notes/daily"
weekly_output_dir: "~/Documents/notes/Weekly"
meeting_notes_output_dir: "~/Documents/notes/meetingnotes"
base_url: "https://api.openai.com/v1/"
api_key: ""
reminders_list: ""
model: "gpt-4o"
chunking_model: "gpt-4o-mini"
learnings_file: "~/Documents/notes/jrnl/learnings.md"
learnings_output_dir: "~/Documents/notes/learnings"

notes_base_dir: "~/Documents/notes" # Base directory for all notes

# Knowledge base settings
knowledge_base:
  exclude_patterns:
    - "*.excalidraw.md" # Exclude Excalidraw files
    - "templates/*" # Exclude template directory
    - ".obsidian/*" # Exclude Obsidian config
    - ".trash/*" # Exclude trash
    - ".git/*" # Exclude git directory
    - ".smart-connections" # Exclude third-party plugin data
    - ".smart-env"
    - ".tmp.drivedownload"
    - ".tmp.driveupload"
    - ".vector_store"

# Vector store settings
vector_store:
  similarity_threshold: 0.60
  hnsw_config:
    ef_construction: 800    # Increase from default 400
    ef_search: 400         # Increase from default 200
    m: 256                # Increase from default 128
  path: "~/.vector_store" # Local ChromaDB storage
  chunk_size_min: 50 # Minimum characters per chunk
  chunk_size_max: 500 # Maximum characters per chunk

# Embeddings configuration
embeddings:
  model_type: "ollama" # Options: openai, huggingface, huggingface_instruct, cohere, ollama
  model_name: "mxbai-embed-large" # Model name for the selected type
  batch_size: 100 # Number of texts to embed at once
  # Ollama-specific configuration
  ollama_config:
    base_url: "http://localhost:11434"
    num_ctx: 512
    num_thread: 4 # Adjust based on your CPU cores if needed

# Chunking configuration
chunking_config:
  recursive:
    chunk_size: 300 # Reduced for better focus
    chunk_overlap: 100 # Increased for context
    separators: ["\n\n", "\n### ", "\n## ", "\n# ", "\n", ". ", "? ", "! ", "; "] # Natural breaks

# Search settings
search:
  default_limit: 10 # Default number of results to return
  preview_length: 200 # Number of characters to show in previews
  thresholds:
    default: 0.35 # Only show results with >35% similarity
    tag_search: 0.30 # More lenient threshold for tag searches
    date_search: 0.30 # More lenient threshold for date searches
    content_search: 0.40 # Stricter threshold for content searches

# Display settings
display:
  date_format: "%Y-%m-%d" # Format for displaying dates
  preview_length: 100 # Length of preview text in characters
  graph:
    enabled: true # Whether to enable graph visualization
    format: "mermaid" # Graph format (mermaid only for now)

# Logging settings
logging:
  level: "INFO" # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
